apiVersion: v1
kind: Service
metadata:
  name: $APPNAME-service
  labels:
    app: $APPNAME
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: $APPNAME-$TARGET_ENV
    role: $TARGET_ENV
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080