apiVersion: v1
kind: Service
metadata:
  name: $APPNAME-test-$TARGET_ENV
  labels:
    app: $APPNAME
spec:
  type: LoadBalancer
  selector:
    app: $APPNAME-$TARGET_ENV
    role: $TARGET_ENV
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP